name: Deploy bicep

on:
  workflow_dispatch:
    inputs:
      buildPath:
        required: true
        type: string
      subscriptionId:
        required: true
        type: string

  workflow_call:
    inputs:
      buildPath:
        required: true
        type: string
      subscriptionId:
        required: true
        type: string

env:
  AZURE_SERVICE_NAME: 'tidslog'
  AZURE_SERVICE_PACKAGE_PATH: './publish'

jobs:

  build-and-deploy:
    runs-on: windows-latest
    steps:
    
    - name: tjek out
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build ".\TimeRegistration.sln" --configuration Release --no-restore --force

    - name: Publish
      run: dotnet publish ".\TimeRegistration\TimeRegistration\TimeRegistration.csproj" --configuration Release --no-build --output '${{ env.AZURE_SERVICE_PACKAGE_PATH }}'

    - uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Bicep file
      uses: azure/arm-deploy@v2
      with:
        scope: subscription
        region: northeurope
        subscriptionId: ${{ inputs.subscriptionId }}
        template: ${{ inputs.buildPath }}/bicep/main.bicep
        parameters: 'resourceGroupLocation=westeurope resourceGroupName=Timeregistration-UI'
        failOnStdErr: false

    - name: Deployment
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_SERVICE_NAME }}
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_SERVICE_PACKAGE_PATH }}