on: 
  workflow_dispatch:
    inputs:
      buildPath:
        required: true
        type: string
      subscriptionId:
        required: true
        type: string

name: Run Azure Login With a Service Principal Secret

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - name: tjek out
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: latest
        inlineScript: |
          az account show

    - name: Deploy Bicep file
      uses: azure/arm-deploy@v2
      with:
        scope: subscription
        subscriptionId: ${{ inputs.subscriptionId }}
        template: ${{ inputs.buildPath }}/Bicep/main.bicep
        parameters: 'storagePrefix=mystore storageSKU=Standard_LRS'
        failOnStdErr: false