name: mainpipline

on: workflow_dispatch

jobs:
  run-tests:
    uses: ./.github/workflows/suprot.dotnet-test.yaml

  validate-pipline:
    needs: [run-tests]
    if: always()
    runs-on: ubuntu-latest
    steps: 
      - name: validate privaios jobs
        shell: pwsh
        run: |
          $status = "${{ needs.run-tests.result }}" -ne "failure"
          Write-Host "${{ needs.run-tests.outputs.BuildParh }}"
          if($status)
          {
            exit
          }
          else
          {
            throw
          }

  build-deploy:
    needs: [validate-pipline, run-tests]
    uses: ./.github/workflows/deploy.deploy-bicep.yaml
    with:
      buildPath: '${{ needs.run-tests.outputs.BuildParh }}'
      subscriptionId: 'cb669899-ef90-41ee-a679-686c45a3d93f'
    secrets: inherit
