name: mainpipline

on: workflow_dispatch

jobs:
  setup-worksapce:
    name: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/suprot.dotnet.yml