name: mainpipline

on: workflow_dispatch

jobs:
  run-tests:
    uses: ./.github/workflows/suprot.dotnet-test.yaml


  test-value:
    runs-on: ubuntu-latest
    steps: 
      shell: pwsh
      run: |
        Write-Output "::set-output name=GREET::$Parh"

  validate-pipline:
    needs: [run-tests, test-value]
    if: always()
    runs-on: ubuntu-latest
    steps: 
      - name: validate privaios jobs
        shell: pwsh
        run: |
          $status = "${{ needs.run-tests.result }}" -ne "failure"
          if($status)
          {
            exit
          }
          else
          {
            throw
          }