# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  workflow_call:
    outputs:
      BuildPath:
        description: "base oath to resoureces"
        value: ${{ jobs.reusable_workflow_job.outputs.BuildPath }}

jobs:
  reusable_workflow_job:
    runs-on: windows-latest
    outputs:
      BuildPath: ${{ steps.vars.outputs.Path }}
    steps:
    - uses: actions/checkout@v4
  
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore --force

    - name: Test
      run: dotnet test --configuration Release --no-build --verbosity normal
      
    - name: get path to main.bicep
      shell: pwsh
      id: vars
      run: |
        $Path = Resolve-Path -path ".github\bin\Release\net*"
        $base = Resolve-Path -path ".\"
        $Path = $Path.Path.Replace("$base", "." )
        echo ::set-output name=Parh::$( $Path)
        Write-Output "Path=$($Path)" >> $Env:GITHUB_OUTPUT

    - name: test parameters
      shell: pwsh
      run: |
        Write-Host "${{ steps.vars.outputs.Path }}"