name: Deploy bicep

on:
  workflow_call:

jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: get path to main.bicep
      shell: pwsh
      id: vars
      run: |
        $Parh = Resolve-Path -path ".github\bin\Release\net*"
        Write-Output "PATH=$Parh" >> $GITHUB_OUTPUT

    - name: Log into Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Bicep file
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: 'cb669899-ef90-41ee-a679-686c45a3d93f'
        template: ${{ steps.vars.outputs.docker_tag }}/Bicep/main.bicep
        parameters: 'storagePrefix=mystore storageSKU=Standard_LRS'
        failOnStdErr: false