name: mainpipline

on: workflow_dispatch

jobs:
  run-tests:
    uses: ./.github/workflows/suprot.dotnet-test.yaml

  validate-pipline:
    needs: [run-tests]
    if: always()
    runs-on: ubuntu-latest
    steps: 
      - run: echo ${{ needs.run-tests }}