name: mainpipline

on: workflow_dispatch

jobs:
  run-tests:
    uses: ./.github/workflows/suprot.dotnet-test.yaml

  validate-pipline:
    if: success()
    needs: [run-tests]
    steps: 
      - run: echo ${{ github.job }}