name: mainpipline

on: workflow_dispatch

jobs:
  run-tests:
    uses: ./.github/workflows/suprot.dotnet-test.yaml

  validate-pipline:
    needs: [run-tests]
    if: always()
    runs-on: ubuntu-latest
    steps: 
      - name: validate privaios jobs
        shell: pwsh
        run: |
          $status = "${{ needs.run-tests.result }}" -ne "failure"
          Write-Host "${{ needs.run-tests.outputs.Parh }}"
          if($status)
          {
            exit
          }
          else
          {
            throw
          }