name: mainpipline

on: workflow_dispatch

jobs:
  setup-worksapce:
    name: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup workspace
        shell: pwsh
        run: |
          Move-Item -Path ".\.github\workflows\suprot\dotnet.yml" -Destination ".\.github\workflows"

      - uses: ./.github/workflows/dotnet.yml