name: mainpipline

on: workflow_dispatch

jobs:
  setup-worksapce:
    name: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup workspace
        shell: pwsh
        run: |
          New-Item -Path ".\.github\workflows\supro" -ItemType "directory"
          Move-Item -Path ".\.github\workflows\dotnet.yml" -Destination ".\.github\workflows\suprot"

  call-workflow-passing-data:
    needs: setup-worksapce
    uses: ./.github/workflows/dotnet.yml