# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  workflow_call:
    outputs:
      BuildParh:
        description: "base oath to resoureces"
        value: ${{ jobs.reusable_workflow_job.outputs.BuildParh }}

jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    outputs:
      BuildParh: ${{ steps.vars.outputs.Parh }}
    steps:
    - uses: actions/checkout@v4
  
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --configuration Release --no-build --verbosity normal
      
    - name: get path to main.bicep
      shell: pwsh
      id: vars
      run: |
        $Parh = Resolve-Path -path ".github\bin\Release\net*"
        echo ::set-output name=Parh::$( $Parh)
        Write-Output "Parh=$($Parh)" >> $Env:GITHUB_OUTPUT

    - name: test parameters
      shell: pwsh
      run: |
        Write-Host "${{ steps.vars.outputs.Parh }}"